spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      자동으로 테이블을 만들어주는 모드. 애플리케이션 생성 시점에 가지고있던 엔티티 다 지우고 새로 생성
      ddl-auto: create
#      얘는 테이블이 그대로 남아있게 된다.
#      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true    --> System.out에 찍기 때문에 안 써야한다.
        format_sql: true
        default_batch_fetch_size: 100 # 한 번에 가져오게 된다. 이 옵션은 웬만하면 무조건 켜놓자. 한 번에 인 쿼리로 유저의 오더 아이템스를 한 방에 가져오게 된다. 미리 몇 개의 쿼리를 땡겨올 것인지. in 쿼리의 개수를 말한다. 아이템이 1000개라면 쿼리가 10개 나오게 된다. 1 + n + n이 1 + 1 + 1이 돼버린다.
        # 사이즈 정하는 게 중요. 맥시멈은 1000개다. 1000개 넘어가면 오류를 일으키는 경우가 있게 된다. 100 ~ 1000 사이가 좋다. 순간 부하를 얼마나 견딜 수 있는지를 고려하여 결정해야한다.

logging:
  level:
    # 얘는 로그를 통해 SQL 찍는걸 보여준다.
    org.hibernate.SQL: debug
    # 얘를 써주면 밑에 binding parameter 해서 순서와 타입, 파라미터 값을 찍어준다.
    org.hibernate.type: trace
