spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      자동으로 테이블을 만들어주는 모드. 애플리케이션 생성 시점에 가지고있던 엔티티 다 지우고 새로 생성
      ddl-auto: create
#      얘는 테이블이 그대로 남아있게 된다.
#      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true    --> System.out에 찍기 때문에 안 써야한다.
        format_sql: true

logging:
  level:
    # 얘는 로그를 통해 SQL 찍는걸 보여준다.
    org.hibernate.SQL: debug
    # 얘를 써주면 밑에 binding parameter 해서 순서와 타입, 파라미터 값을 찍어준다.
    org.hibernate.type: trace
